# .github/workflows/main.yml

name: Generate Fiery Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # ADD THIS PERMISSIONS BLOCK
    permissions:
      contents: write # Grants write permissions to the GITHUB_TOKEN for this job
      
    steps:
      - uses: actions/checkout@v3

      - name: Generate Fiery Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/fire-snake.svg?color_snake=#B61504,#E33C02,#FF8D00,#FFF000,#FFFFFF&color_dots=#260000

      - name: Push to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: generated new fire snake animation" || exit 0
          git push
